<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Bank Deposits Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; color: #333; }
        .header { border-bottom: 3px solid #1d4ed8; padding-bottom: 15px; margin-bottom: 20px; }
        .header h1 { margin: 0; color: #1d4ed8; font-size: 24px; }
        .header p { margin: 5px 0 0 0; color: #666; font-size: 12px; }
        .summary { background: #dbeafe; padding: 15px; border-radius: 8px; margin-bottom: 20px; border-left: 4px solid #1d4ed8; }
        .summary-item { display: inline-block; margin-right: 30px; }
        .summary-label { font-size: 11px; color: #666; text-transform: uppercase; font-weight: bold; }
        .summary-value { font-size: 18px; font-weight: bold; color: #1d4ed8; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: #f1f5f9; padding: 10px; text-align: left; font-size: 11px; font-weight: bold; color: #475569; border-bottom: 2px solid #e2e8f0; text-transform: uppercase; }
        td { padding: 10px; border-bottom: 1px solid #e2e8f0; font-size: 12px; }
        tr:last-child td { border-bottom: none; }
        .amount { font-weight: bold; color: #1d4ed8; }
        .status-verified { color: #15803d; font-weight: bold; }
        .status-pending { color: #a16207; font-weight: bold; }
        .status-rejected { color: #b91c1c; font-weight: bold; }
        .footer { margin-top: 30px; padding-top: 15px; border-top: 1px solid #e2e8f0; font-size: 10px; color: #666; text-align: center; }
        .generated { color: #999; font-size: 10px; margin-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Bank Deposits Report</h1>
        <p>{{ $orgName }} — eVoucher Food Support Platform</p>
    </div>
    
    <div class="summary">
        <div class="summary-item">
            <div class="summary-label">Total Verified Deposits</div>
            <div class="summary-value">£{{ number_format($totalDeposits, 2) }}</div>
        </div>
        <div class="summary-item">
            <div class="summary-label">Total Deposits</div>
            <div class="summary-value">{{ count($bankDeposits) }}</div>
        </div>
        <div class="summary-item">
            <div class="summary-label">Report Date</div>
            <div class="summary-value">{{ now()->format('d M Y') }}</div>
        </div>
    </div>
    
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Amount</th>
                <th>Reference</th>
                <th>Status</th>
                <th>Verified On</th>
            </tr>
        </thead>
        <tbody>
            @foreach($bankDeposits as $deposit)
            <tr>
                <td>{{ $deposit->created_at->format('d M Y H:i') }}</td>
                <td class="amount">£{{ number_format($deposit->amount, 2) }}</td>
                <td>{{ $deposit->reference }}</td>
                <td>
                    @if($deposit->status === 'verified')
                        <span class="status-verified">✓ Verified</span>
                    @elseif($deposit->status === 'pending')
                        <span class="status-pending">⏱ Pending</span>
                    @else
                        <span class="status-rejected">✗ Rejected</span>
                    @endif
                </td>
                <td>{{ $deposit->verified_at ? $deposit->verified_at->format('d M Y') : '-' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    
    <div class="footer">
        <p>This is an official report generated by the eVoucher Food Support Platform.</p>
        <div class="generated">Generated on {{ now()->format('d M Y \a\t H:i:s') }}</div>
    </div>
</body>
</html>
