<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Fund Loads Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; color: #333; }
        .header { border-bottom: 3px solid #16a34a; padding-bottom: 15px; margin-bottom: 20px; }
        .header h1 { margin: 0; color: #16a34a; font-size: 24px; }
        .header p { margin: 5px 0 0 0; color: #666; font-size: 12px; }
        .summary { background: #f0fdf4; padding: 15px; border-radius: 8px; margin-bottom: 20px; border-left: 4px solid #16a34a; }
        .summary-item { display: inline-block; margin-right: 30px; }
        .summary-label { font-size: 11px; color: #666; text-transform: uppercase; font-weight: bold; }
        .summary-value { font-size: 18px; font-weight: bold; color: #16a34a; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: #f1f5f9; padding: 10px; text-align: left; font-size: 11px; font-weight: bold; color: #475569; border-bottom: 2px solid #e2e8f0; text-transform: uppercase; }
        td { padding: 10px; border-bottom: 1px solid #e2e8f0; font-size: 12px; }
        tr:last-child td { border-bottom: none; }
        .amount { font-weight: bold; color: #16a34a; }
        .footer { margin-top: 30px; padding-top: 15px; border-top: 1px solid #e2e8f0; font-size: 10px; color: #666; text-align: center; }
        .generated { color: #999; font-size: 10px; margin-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Fund Loads Report</h1>
        <p>{{ $orgName }} — eVoucher Food Support Platform</p>
    </div>
    
    <div class="summary">
        <div class="summary-item">
            <div class="summary-label">Total Funds Loaded</div>
            <div class="summary-value">£{{ number_format($totalFundsLoaded, 2) }}</div>
        </div>
        <div class="summary-item">
            <div class="summary-label">Total Transactions</div>
            <div class="summary-value">{{ count($fundLoads) }}</div>
        </div>
        <div class="summary-item">
            <div class="summary-label">Report Date</div>
            <div class="summary-value">{{ now()->format('d M Y') }}</div>
        </div>
    </div>
    
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Amount</th>
                <th>Reference</th>
                <th>Loaded By</th>
                <th>Notes</th>
            </tr>
        </thead>
        <tbody>
            @foreach($fundLoads as $load)
            <tr>
                <td>{{ $load->created_at->format('d M Y H:i') }}</td>
                <td class="amount">£{{ number_format($load->amount, 2) }}</td>
                <td>{{ $load->reference }}</td>
                <td>{{ $load->admin->name ?? 'System' }}</td>
                <td>{{ $load->notes ?? '-' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    
    <div class="footer">
        <p>This is an official report generated by the eVoucher Food Support Platform.</p>
        <div class="generated">Generated on {{ now()->format('d M Y \a\t H:i:s') }}</div>
    </div>
</body>
</html>
